// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Nekitker
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using Jotunn.Configs;
using Jotunn.Entities;
using Jotunn.Managers;
using Jotunn.Utils;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.Networking;

namespace SaunaMod
{
    /// Rendering parameters for autogenerated icons of new pieces.
    /// While the editor is enabled, changes apply live and immediately redraw hammer icons.
    internal static class SaunaPieceIconTuning
    {
        // Icon camera angles captured from the final editor dump.
        // Rendering is centered using Renderer.bounds after rotation,
        // so the model stays centered at these angles.
        public static float WrisksYaw = 285f;
        public static float WrisksPitch = 0f;
        public static float WrisksRoll = -15f;
        public static float WrisksOffsetX = 0f;
        public static float WrisksOffsetY = 0f;
        public static float WrisksDistance = 0f;
        public static float WrisksScale = 2.15f;

        public static float BucketYaw = -110f;
        public static float BucketPitch = -10f;
        public static float BucketRoll = -25f;
        public static float BucketOffsetX = 0f;
        public static float BucketOffsetY = 0f;
        public static float BucketDistance = 0f;
        public static float BucketScale = 1f;

        // Starting view, same facing as the whisks: the side away from the wall turned
        // towards the camera. Not yet tuned in the editor.
        public static float TowelRackYaw = 285f;
        public static float TowelRackPitch = 0f;
        public static float TowelRackRoll = 0f;
        public static float TowelRackOffsetX = 0f;
        public static float TowelRackOffsetY = 0f;
        public static float TowelRackDistance = 0f;
        public static float TowelRackScale = 1f;
    }
}
