// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Nekitker
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using Jotunn.Configs;
using Jotunn.Entities;
using Jotunn.Managers;
using Jotunn.Utils;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.Networking;

namespace SaunaMod
{
    /// Procedurally builds the stone dome and the pile of hot stones inside it.
    internal static class StoveVisual
    {
        public const string DomeName = "sauna_stone_visual";
        public const string FloorName = "sauna_floor_visual";
        public const string LavaName = "sauna_lava_visual";
        public const string CoalName = "sauna_coal_visual";

        public static readonly List<GameObject> Candidates = new List<GameObject>();
        public static readonly List<GameObject> LavaCandidates = new List<GameObject>();

        /// Look up by name because list indexes may shift after patches or other mods.
        public const string PreferredStone = "StoneRock";
        public const string PreferredLava = "UnstableLavaRock";

        /// What replaces the hot stones when the stove goes out.
        public const string PreferredCoal = "Coal";

        private static readonly string[] LavaKeywords =
        {
            "lava", "magma", "ember", "molten", "glowing", "coal"
        };

        // ---- dome ----
        public static int StoneIndex = 0;
        public static float StoneSize = 0.45f;
        public static float BaseRadius = 0.65f;
        public static float TopRadius = 0.31f;
        public static float Height = 0.80f;
        public static int Layers = 5;
        public static int CountBase = 12;
        public static float OpeningWidth = 65f;
        public static int OpeningLayers = 2;
        public static float SizeJitter = 0.10f;
        public static float Tilt = 30f;
        public static int Seed = 12345;

        // ---- layer of ordinary stones on the bottom ----
        // Uses the same stone prefab as the dome, but size and density are configured separately.
        public static float FloorStoneSize = 0.30f;
        public static int FloorCount = 28;
        public static float FloorRadius = 0.56f;
        public static float FloorOffsetY = -0.06f;

        // ---- hot stones inside ----
        public static int LavaIndex = 0;
        public static float LavaSize = 0.24f;
        public static int LavaCount = 12;
        public static float LavaRadius = 0.33f;
        public static float LavaOffsetY = 0.04f;

        // ---- cooled coals replacing the hot stones ----
        // The pile uses the same positions as the hot stones,
        // so extinguishing changes only the appearance, not the shape.
        public static float CoalSize = 0.20f;

        // ---- fire, light, and heat ----
        public static float FireOffsetY = -0.20f;

        /// IMPORTANT: zero scales the heat-zone collider to zero and the stove stops providing heat.
        /// Use FlameSet, not scale, to hide the flames.
        public static float FireScale = 0.25f;

        /// Scale of the visible flame particle systems enabled by FlameSet.
        /// Does not change the size or position of the Fireplace root or heat zone.
        public static float FlameSize = 0.50f;

        /// Multiplier for the heat-zone radius. It is scaled separately from the flames,
        /// because FireScale shrinks the entire fire node together with the heat collider.
        /// A value of 4.0 with FireScale 0.25 restores the original iron firepit heat radius.
        public static float WarmthRadius = 2.5f;

        /// Separate vertical offset for visible flames only.
        /// Useful when the lower part of the fire visually starts below the stones.
        public static float FlameOffsetY = 0.56f;

        // ---- autogenerated build-piece icon view ----
        // The dome opening faces +X, so the desired view is selected with Yaw.
        public static float IconYaw = 270f;
        public static float IconPitch = 0f;

        /// 1 = try to include the flame in the icon. Particle systems need simulation time,
        /// so the result may depend on the Jotunn version.
        public static int IconFlame = 0;

        /// 0 = no flames, 1 = low flames, 2 = low + high flames, 3 = everything including smoke wisps.
        public static int FlameSet = 2;

        private static Mesh _domeMesh;
        private static Material[] _domeMaterials;
        private static Mesh _floorMesh;
        private static Material[] _floorMaterials;
        private static Mesh _lavaMesh;
        private static Material[] _lavaMaterials;
        private static Mesh _coalMesh;
        private static Material[] _coalMaterials;

        public static void CollectCandidates()
        {
            Candidates.Clear();
            LavaCandidates.Clear();

            if (ZNetScene.instance == null)
            {
                return;
            }

            List<KeyValuePair<float, GameObject>> stones = new List<KeyValuePair<float, GameObject>>();
            List<KeyValuePair<float, GameObject>> lava = new List<KeyValuePair<float, GameObject>>();

            foreach (GameObject p in ZNetScene.instance.m_prefabs)
            {
                if (p == null)
                {
                    continue;
                }

                MeshFilter mf = p.GetComponentInChildren<MeshFilter>(true);
                if (mf == null || mf.sharedMesh == null)
                {
                    continue;
                }

                UnityEngine.Vector3 size = mf.sharedMesh.bounds.size;
                float max = Mathf.Max(size.x, Mathf.Max(size.y, size.z));

                if (max < 0.1f || max > 4f)
                {
                    continue;
                }

                string lower = p.name.ToLowerInvariant();

                if (lower.Contains("rock") || lower.Contains("stone"))
                {
                    stones.Add(new KeyValuePair<float, GameObject>(max, p));
                }

                foreach (string key in LavaKeywords)
                {
                    if (lower.Contains(key))
                    {
                        lava.Add(new KeyValuePair<float, GameObject>(max, p));
                        break;
                    }
                }
            }

            stones.Sort((a, b) => a.Key.CompareTo(b.Key));
            lava.Sort((a, b) => a.Key.CompareTo(b.Key));

            foreach (KeyValuePair<float, GameObject> kv in stones)
            {
                Candidates.Add(kv.Value);
            }

            foreach (KeyValuePair<float, GameObject> kv in lava)
            {
                LavaCandidates.Add(kv.Value);
            }

            StoneIndex = FindByName(Candidates, PreferredStone, StoneIndex, "stone");
            LavaIndex = FindByName(LavaCandidates, PreferredLava, LavaIndex, "lava");

            Invalidate();
        }

        private static int FindByName(List<GameObject> list, string wanted, int fallback, string label)
        {
            for (int i = 0; i < list.Count; i++)
            {
                if (list[i].name == wanted)
                {
                    Jotunn.Logger.LogInfo($"{label} '{wanted}' found at index {i} of {list.Count}");
                    return i;
                }
            }

            Jotunn.Logger.LogWarning($"{label} '{wanted}' NOT found among {list.Count}, using index {fallback}");
            return fallback;
        }

        public static string CurrentStoneName()
        {
            if (Candidates.Count == 0)
            {
                return "none";
            }

            return Candidates[Mathf.Clamp(StoneIndex, 0, Candidates.Count - 1)].name;
        }

        public static string CurrentLavaName()
        {
            List<GameObject> list = LavaCandidates.Count > 0 ? LavaCandidates : Candidates;

            if (list.Count == 0)
            {
                return "none";
            }

            return list[Mathf.Clamp(LavaIndex, 0, list.Count - 1)].name;
        }

        public static void Invalidate()
        {
            if (_domeMesh != null)
            {
                UnityEngine.Object.Destroy(_domeMesh);
                _domeMesh = null;
            }

            if (_floorMesh != null)
            {
                UnityEngine.Object.Destroy(_floorMesh);
                _floorMesh = null;
            }

            if (_lavaMesh != null)
            {
                UnityEngine.Object.Destroy(_lavaMesh);
                _lavaMesh = null;
            }

            if (_coalMesh != null)
            {
                UnityEngine.Object.Destroy(_coalMesh);
                _coalMesh = null;
            }

            _domeMaterials = null;
            _floorMaterials = null;
            _lavaMaterials = null;
            _coalMaterials = null;
        }

        private static bool GetSource(GameObject source, out Mesh mesh, out Material[] materials, out float meshMax)
        {
            mesh = null;
            materials = null;
            meshMax = 0f;

            if (source == null)
            {
                return false;
            }

            MeshFilter mf = source.GetComponentInChildren<MeshFilter>(true);
            MeshRenderer mr = source.GetComponentInChildren<MeshRenderer>(true);

            if (mf == null || mf.sharedMesh == null || mr == null || mr.sharedMaterials.Length == 0)
            {
                return false;
            }

            UnityEngine.Vector3 size = mf.sharedMesh.bounds.size;
            meshMax = Mathf.Max(size.x, Mathf.Max(size.y, size.z));

            if (meshMax <= 0.001f)
            {
                return false;
            }

            mesh = mf.sharedMesh;
            materials = new[] { mr.sharedMaterials[0] };
            return true;
        }

        /// One shared dome mesh for all sauna stoves in the world.
        public static Mesh GetDomeMesh(out Material[] materials)
        {
            materials = _domeMaterials;

            if (_domeMesh != null && _domeMaterials != null)
            {
                return _domeMesh;
            }

            if (Candidates.Count == 0)
            {
                return null;
            }

            GameObject source = Candidates[Mathf.Clamp(StoneIndex, 0, Candidates.Count - 1)];

            Mesh srcMesh;
            Material[] srcMaterials;
            float meshMax;

            if (!GetSource(source, out srcMesh, out srcMaterials, out meshMax))
            {
                return null;
            }

            float baseScale = StoneSize / meshMax;

            List<CombineInstance> parts = new List<CombineInstance>();

            // Fixed random seed so the stove looks identical for every player.
            UnityEngine.Random.State saved = UnityEngine.Random.state;
            UnityEngine.Random.InitState(Seed);

            int layers = Mathf.Max(1, Layers);
            int countBase = Mathf.Max(3, CountBase);

            for (int layer = 0; layer < layers; layer++)
            {
                float t = layers > 1 ? (float)layer / (layers - 1) : 0f;
                float radius = Mathf.Lerp(BaseRadius, TopRadius, t);
                float y = Height * t;

                int count = Mathf.Max(3, Mathf.RoundToInt(countBase * radius / Mathf.Max(0.01f, BaseRadius)));
                float step = 360f / count;
                float offset = layer * step * 0.5f;

                for (int i = 0; i < count; i++)
                {
                    float angle = offset + i * step;

                    if (layer < OpeningLayers && IsInOpening(angle))
                    {
                        continue;
                    }

                    float rad = angle * Mathf.Deg2Rad;
                    UnityEngine.Vector3 pos = new UnityEngine.Vector3(
                        Mathf.Cos(rad) * radius,
                        y,
                        Mathf.Sin(rad) * radius);

                    UnityEngine.Quaternion face = UnityEngine.Quaternion.Euler(0f, -angle, 0f);
                    UnityEngine.Quaternion lean = UnityEngine.Quaternion.Euler(0f, 0f, Tilt * t);
                    UnityEngine.Quaternion noise = UnityEngine.Quaternion.Euler(
                        UnityEngine.Random.Range(-20f, 20f),
                        UnityEngine.Random.Range(-180f, 180f),
                        UnityEngine.Random.Range(-20f, 20f));

                    float jitter = 1f + UnityEngine.Random.Range(-SizeJitter, SizeJitter);

                    CombineInstance ci = new CombineInstance();
                    ci.mesh = srcMesh;
                    ci.subMeshIndex = 0;
                    ci.transform = UnityEngine.Matrix4x4.TRS(
                        pos,
                        face * lean * noise,
                        UnityEngine.Vector3.one * baseScale * jitter);

                    parts.Add(ci);
                }
            }

            UnityEngine.Random.state = saved;

            if (parts.Count == 0)
            {
                return null;
            }

            Mesh combined = new Mesh();
            combined.name = "sauna_dome";
            combined.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            combined.CombineMeshes(parts.ToArray(), true, true);
            combined.RecalculateBounds();

            _domeMesh = combined;
            _domeMaterials = srcMaterials;
            materials = _domeMaterials;

            Jotunn.Logger.LogInfo($"dome mesh: {parts.Count} stones, {combined.vertexCount} verts, " +
                $"source={source.name}");

            return _domeMesh;
        }

        /// One dense layer of ordinary stones on the bottom of the stove.
        /// The layout is deterministic, so it looks the same for every player.
        public static Mesh GetFloorMesh(out Material[] materials)
        {
            materials = _floorMaterials;

            if (_floorMesh != null && _floorMaterials != null)
            {
                return _floorMesh;
            }

            if (Candidates.Count == 0 || FloorCount <= 0)
            {
                return null;
            }

            GameObject source = Candidates[Mathf.Clamp(StoneIndex, 0, Candidates.Count - 1)];

            Mesh srcMesh;
            Material[] srcMaterials;
            float meshMax;

            if (!GetSource(source, out srcMesh, out srcMaterials, out meshMax))
            {
                return null;
            }

            float baseScale = FloorStoneSize / meshMax;
            List<CombineInstance> parts = new List<CombineInstance>();

            UnityEngine.Random.State saved = UnityEngine.Random.state;
            UnityEngine.Random.InitState(Seed + 333);

            // Sunflower distribution: points fill the circle evenly instead of clumping in the center.
            const float goldenAngle = 137.50776f;

            for (int i = 0; i < FloorCount; i++)
            {
                float t = (i + 0.5f) / Mathf.Max(1f, FloorCount);
                float radius = FloorRadius * Mathf.Sqrt(t);
                float angle = i * goldenAngle + UnityEngine.Random.Range(-10f, 10f);
                float rad = angle * Mathf.Deg2Rad;

                UnityEngine.Vector3 pos = new UnityEngine.Vector3(
                    Mathf.Cos(rad) * radius,
                    FloorOffsetY + UnityEngine.Random.Range(-0.02f, 0.02f),
                    Mathf.Sin(rad) * radius);

                // Stones lie almost flat, with random Y rotation and a slight tilt.
                UnityEngine.Quaternion rot = UnityEngine.Quaternion.Euler(
                    UnityEngine.Random.Range(-8f, 8f),
                    UnityEngine.Random.Range(-180f, 180f),
                    UnityEngine.Random.Range(-8f, 8f));

                float jitter = 1f + UnityEngine.Random.Range(-0.12f, 0.12f);

                CombineInstance ci = new CombineInstance();
                ci.mesh = srcMesh;
                ci.subMeshIndex = 0;
                ci.transform = UnityEngine.Matrix4x4.TRS(
                    pos, rot, UnityEngine.Vector3.one * baseScale * jitter);

                parts.Add(ci);
            }

            UnityEngine.Random.state = saved;

            if (parts.Count == 0)
            {
                return null;
            }

            Mesh combined = new Mesh();
            combined.name = "sauna_floor";
            combined.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            combined.CombineMeshes(parts.ToArray(), true, true);
            combined.RecalculateBounds();

            _floorMesh = combined;
            _floorMaterials = srcMaterials;
            materials = _floorMaterials;

            Jotunn.Logger.LogInfo($"floor mesh: {parts.Count} stones, source={source.name}");

            return _floorMesh;
        }

        /// Pile of hot stones in the center.
        /// The cooled pile uses coal at the same positions as the hot stones.
        public static Mesh GetCoalMesh(out Material[] materials)
        {
            materials = _coalMaterials;

            if (_coalMesh != null && _coalMaterials != null)
            {
                return _coalMesh;
            }

            if (LavaCount <= 0)
            {
                return null;
            }

            GameObject source = ZNetScene.instance != null
                ? ZNetScene.instance.GetPrefab(PreferredCoal)
                : null;

            if (source == null)
            {
                source = PrefabManager.Instance.GetPrefab(PreferredCoal);
            }

            Mesh srcMesh;
            Material[] srcMaterials;
            float meshMax;

            if (!GetSource(source, out srcMesh, out srcMaterials, out meshMax))
            {
                Jotunn.Logger.LogWarning($"coal '{PreferredCoal}' mesh not found, cold stove keeps lava look");
                return null;
            }

            float baseScale = CoalSize / meshMax;

            List<CombineInstance> parts = new List<CombineInstance>();

            // Use the same seed and random-number order as GetLavaMesh,
            // so the coals appear exactly where the hot stones were.
            UnityEngine.Random.State saved = UnityEngine.Random.state;
            UnityEngine.Random.InitState(Seed + 777);

            for (int i = 0; i < LavaCount; i++)
            {
                UnityEngine.Vector2 flat = UnityEngine.Random.insideUnitCircle * LavaRadius;

                UnityEngine.Vector3 pos = new UnityEngine.Vector3(
                    flat.x,
                    LavaOffsetY + UnityEngine.Random.Range(0f, LavaSize * 0.5f),
                    flat.y);

                UnityEngine.Quaternion rot = UnityEngine.Quaternion.Euler(
                    UnityEngine.Random.Range(-180f, 180f),
                    UnityEngine.Random.Range(-180f, 180f),
                    UnityEngine.Random.Range(-180f, 180f));

                float jitter = 1f + UnityEngine.Random.Range(-0.25f, 0.25f);

                CombineInstance ci = new CombineInstance();
                ci.mesh = srcMesh;
                ci.subMeshIndex = 0;
                ci.transform = UnityEngine.Matrix4x4.TRS(
                    pos, rot, UnityEngine.Vector3.one * baseScale * jitter);

                parts.Add(ci);
            }

            UnityEngine.Random.state = saved;

            Mesh combined = new Mesh();
            combined.name = "sauna_coal";
            combined.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            combined.CombineMeshes(parts.ToArray(), true, true);
            combined.RecalculateBounds();

            _coalMesh = combined;
            _coalMaterials = srcMaterials;
            materials = _coalMaterials;

            Jotunn.Logger.LogInfo($"coal mesh: {parts.Count} pieces, source={source.name}");

            return _coalMesh;
        }

        public static Mesh GetLavaMesh(out Material[] materials)
        {
            materials = _lavaMaterials;

            if (_lavaMesh != null && _lavaMaterials != null)
            {
                return _lavaMesh;
            }

            List<GameObject> list = LavaCandidates.Count > 0 ? LavaCandidates : Candidates;

            if (list.Count == 0 || LavaCount <= 0)
            {
                return null;
            }

            GameObject source = list[Mathf.Clamp(LavaIndex, 0, list.Count - 1)];

            Mesh srcMesh;
            Material[] srcMaterials;
            float meshMax;

            if (!GetSource(source, out srcMesh, out srcMaterials, out meshMax))
            {
                return null;
            }

            float baseScale = LavaSize / meshMax;

            List<CombineInstance> parts = new List<CombineInstance>();

            UnityEngine.Random.State saved = UnityEngine.Random.state;
            UnityEngine.Random.InitState(Seed + 777);

            for (int i = 0; i < LavaCount; i++)
            {
                UnityEngine.Vector2 flat = UnityEngine.Random.insideUnitCircle * LavaRadius;

                UnityEngine.Vector3 pos = new UnityEngine.Vector3(
                    flat.x,
                    LavaOffsetY + UnityEngine.Random.Range(0f, LavaSize * 0.5f),
                    flat.y);

                UnityEngine.Quaternion rot = UnityEngine.Quaternion.Euler(
                    UnityEngine.Random.Range(-180f, 180f),
                    UnityEngine.Random.Range(-180f, 180f),
                    UnityEngine.Random.Range(-180f, 180f));

                float jitter = 1f + UnityEngine.Random.Range(-0.25f, 0.25f);

                CombineInstance ci = new CombineInstance();
                ci.mesh = srcMesh;
                ci.subMeshIndex = 0;
                ci.transform = UnityEngine.Matrix4x4.TRS(
                    pos, rot, UnityEngine.Vector3.one * baseScale * jitter);

                parts.Add(ci);
            }

            UnityEngine.Random.state = saved;

            Mesh combined = new Mesh();
            combined.name = "sauna_lava";
            combined.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            combined.CombineMeshes(parts.ToArray(), true, true);
            combined.RecalculateBounds();

            _lavaMesh = combined;
            _lavaMaterials = srcMaterials;
            materials = _lavaMaterials;

            Jotunn.Logger.LogInfo($"lava mesh: {parts.Count} stones, source={source.name}");

            return _lavaMesh;
        }

        public static void Build(Transform parent)
        {
            BuildPart(parent, FloorName, GetFloorMesh);
            BuildPart(parent, DomeName, GetDomeMesh);
            BuildPart(parent, LavaName, GetLavaMesh);
            BuildPart(parent, CoalName, GetCoalMesh);
        }

        private delegate Mesh MeshGetter(out Material[] materials);

        private static void BuildPart(Transform parent, string name, MeshGetter getter)
        {
            // Destroy only completes at the end of the frame, so the old object
            // remains among the children with the same name until then. Find may return
            // that object instead of the new one, sending the burning/extinguished state
            // to an object that is about to disappear and leaving the new one visible.
            // Detach and hide the old object first, then destroy it.
            Transform old = parent.Find(name);
            while (old != null)
            {
                old.gameObject.SetActive(false);
                old.SetParent(null, false);
                UnityEngine.Object.Destroy(old.gameObject);
                old = parent.Find(name);
            }

            Material[] materials;
            Mesh mesh = getter(out materials);

            if (mesh == null || materials == null)
            {
                return;
            }

            GameObject go = new GameObject(name);
            go.transform.SetParent(parent, false);
            go.transform.localPosition = UnityEngine.Vector3.zero;
            go.transform.localRotation = UnityEngine.Quaternion.identity;

            MeshFilter mf = go.AddComponent<MeshFilter>();
            mf.sharedMesh = mesh;

            MeshRenderer mr = go.AddComponent<MeshRenderer>();
            mr.sharedMaterials = materials;
            mr.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.On;
        }

        /// Whether this particle system should be visible for the current FlameSet.
        public static bool KeepFlame(string objectName)
        {
            if (FlameSet <= 0)
            {
                return false;
            }

            if (FlameSet >= 3)
            {
                return true;
            }

            string lower = objectName.ToLowerInvariant();

            if (FlameSet >= 2 && lower.Contains("flames"))
            {
                return true;
            }

            return lower.Contains("low_flames");
        }

        private static bool IsInOpening(float angle)
        {
            float a = Mathf.Repeat(angle, 360f);
            if (a > 180f)
            {
                a -= 360f;
            }

            return Mathf.Abs(a) < OpeningWidth * 0.5f;
        }
    }
}
